services:
  discord-docker-status-bot:
    image: ghcr.io/zamnzim/discord-docker-status-bot:latest
    container_name: discord-docker-status-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=your_discord_bot_token_here
      - DISCORD_CHANNEL_ID=your_channel_id_here
      - DOCKER_SERVER_NAME=your_server_name_her
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
